/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPollsCreateRouteImport } from './routes/_authenticated/polls.create'
import { Route as AuthenticatedPollsPollIdRouteImport } from './routes/_authenticated/polls.$pollId'
import { Route as AuthenticatedPollsPollIdAnalyticsRouteImport } from './routes/_authenticated/polls.$pollId.analytics'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPollsCreateRoute =
  AuthenticatedPollsCreateRouteImport.update({
    id: '/polls/create',
    path: '/polls/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPollsPollIdRoute =
  AuthenticatedPollsPollIdRouteImport.update({
    id: '/polls/$pollId',
    path: '/polls/$pollId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPollsPollIdAnalyticsRoute =
  AuthenticatedPollsPollIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedPollsPollIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/polls/$pollId': typeof AuthenticatedPollsPollIdRouteWithChildren
  '/polls/create': typeof AuthenticatedPollsCreateRoute
  '/polls/$pollId/analytics': typeof AuthenticatedPollsPollIdAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/polls/$pollId': typeof AuthenticatedPollsPollIdRouteWithChildren
  '/polls/create': typeof AuthenticatedPollsCreateRoute
  '/polls/$pollId/analytics': typeof AuthenticatedPollsPollIdAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/polls/$pollId': typeof AuthenticatedPollsPollIdRouteWithChildren
  '/_authenticated/polls/create': typeof AuthenticatedPollsCreateRoute
  '/_authenticated/polls/$pollId/analytics': typeof AuthenticatedPollsPollIdAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/polls/$pollId'
    | '/polls/create'
    | '/polls/$pollId/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/polls/$pollId'
    | '/polls/create'
    | '/polls/$pollId/analytics'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/polls/$pollId'
    | '/_authenticated/polls/create'
    | '/_authenticated/polls/$pollId/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/polls/create': {
      id: '/_authenticated/polls/create'
      path: '/polls/create'
      fullPath: '/polls/create'
      preLoaderRoute: typeof AuthenticatedPollsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/polls/$pollId': {
      id: '/_authenticated/polls/$pollId'
      path: '/polls/$pollId'
      fullPath: '/polls/$pollId'
      preLoaderRoute: typeof AuthenticatedPollsPollIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/polls/$pollId/analytics': {
      id: '/_authenticated/polls/$pollId/analytics'
      path: '/analytics'
      fullPath: '/polls/$pollId/analytics'
      preLoaderRoute: typeof AuthenticatedPollsPollIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedPollsPollIdRoute
    }
  }
}

interface AuthenticatedPollsPollIdRouteChildren {
  AuthenticatedPollsPollIdAnalyticsRoute: typeof AuthenticatedPollsPollIdAnalyticsRoute
}

const AuthenticatedPollsPollIdRouteChildren: AuthenticatedPollsPollIdRouteChildren =
  {
    AuthenticatedPollsPollIdAnalyticsRoute:
      AuthenticatedPollsPollIdAnalyticsRoute,
  }

const AuthenticatedPollsPollIdRouteWithChildren =
  AuthenticatedPollsPollIdRoute._addFileChildren(
    AuthenticatedPollsPollIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPollsPollIdRoute: typeof AuthenticatedPollsPollIdRouteWithChildren
  AuthenticatedPollsCreateRoute: typeof AuthenticatedPollsCreateRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPollsPollIdRoute: AuthenticatedPollsPollIdRouteWithChildren,
  AuthenticatedPollsCreateRoute: AuthenticatedPollsCreateRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
